# Threat Model Spec - All Styles Combined
# https://github.com/grokify/threat-model-spec
#
# Import this single file to get all TMS styles
#
# Usage:
#   ...all.d2
#
# Or import individual style files:
#   ...stride.d2
#   ...dfd.d2
#   ...trustboundary.d2
#   ...attackflow.d2

# Import all component styles
...stride.d2
...dfd.d2
...trustboundary.d2
...attackflow.d2
