package diagram

import (
	"fmt"
	"strings"

	"github.com/grokify/threat-model-spec/stride"
)

// Renderer handles D2 code generation from diagrams.
type Renderer struct {
	// IndentString is the string used for indentation (default: "  ").
	IndentString string

	// IncludeComments adds comments to the output.
	IncludeComments bool
}

// NewRenderer creates a new renderer with default settings.
func NewRenderer() *Renderer {
	return &Renderer{
		IndentString:    "  ",
		IncludeComments: true,
	}
}

// Render generates D2 code for the given diagram.
func (r *Renderer) Render(d *Diagram) string {
	var sb strings.Builder

	// Header comment
	if r.IncludeComments && d.Title != "" {
		sb.WriteString("# " + d.Title + "\n")
		sb.WriteString("# Generated by D2TM - https://github.com/grokify/threat-model-spec\n\n")
	}

	// Direction
	if d.Direction != "" {
		sb.WriteString("direction: " + string(d.Direction) + "\n\n")
	}

	// Styles import
	if d.IncludeStyles && d.StylesPath != "" {
		sb.WriteString("# Import D2TM styles\n")
		sb.WriteString("..." + d.StylesPath + "/all.d2\n\n")
	}

	// Render boundaries with their nested elements
	if r.IncludeComments && len(d.Boundaries) > 0 {
		sb.WriteString("# Trust Boundaries\n")
	}

	// Group elements by parent
	elementsByParent := make(map[string][]Element)
	for _, e := range d.Elements {
		elementsByParent[e.ParentID] = append(elementsByParent[e.ParentID], e)
	}

	// Render boundaries (non-nested first)
	for _, b := range d.Boundaries {
		if b.ParentID == "" {
			r.renderBoundary(&sb, d, b, elementsByParent, 0)
		}
	}

	// Render top-level elements (no parent)
	for _, e := range elementsByParent[""] {
		r.renderElement(&sb, e, 0)
	}

	// Render flows
	if len(d.Flows) > 0 {
		sb.WriteString("\n")
		if r.IncludeComments {
			sb.WriteString("# Flows\n")
		}
		for _, f := range d.Flows {
			r.renderFlow(&sb, f)
		}
	}

	// Render standalone threats
	if len(d.Threats) > 0 {
		sb.WriteString("\n")
		if r.IncludeComments {
			sb.WriteString("# Threat Annotations\n")
		}
		for _, t := range d.Threats {
			r.renderThreat(&sb, t)
		}
	}

	return sb.String()
}

func (r *Renderer) renderBoundary(sb *strings.Builder, d *Diagram, b Boundary, elementsByParent map[string][]Element, indent int) {
	prefix := strings.Repeat(r.IndentString, indent)

	// Start boundary
	sb.WriteString(prefix + b.ID + ": " + b.Label + " {\n")

	// Render boundary style
	r.renderBoundaryStyle(sb, b, indent+1)

	// Render nested elements
	for _, e := range elementsByParent[b.ID] {
		r.renderElement(sb, e, indent+1)
	}

	// Render nested boundaries
	for _, nested := range d.Boundaries {
		if nested.ParentID == b.ID {
			sb.WriteString("\n")
			r.renderBoundary(sb, d, nested, elementsByParent, indent+1)
		}
	}

	sb.WriteString(prefix + "}\n\n")
}

func (r *Renderer) renderBoundaryStyle(sb *strings.Builder, b Boundary, indent int) {
	prefix := strings.Repeat(r.IndentString, indent)

	sb.WriteString(prefix + "style: {\n")

	// Default boundary style
	sb.WriteString(prefix + r.IndentString + "stroke-dash: 5\n")

	// Type-specific colors
	switch b.GetEffectiveType() {
	case ExternalBoundary, BreachedBoundary:
		sb.WriteString(prefix + r.IndentString + "stroke: \"#c62828\"\n")
		if b.GetEffectiveType() == BreachedBoundary {
			sb.WriteString(prefix + r.IndentString + "stroke-width: 4\n")
			sb.WriteString(prefix + r.IndentString + "fill: \"#ffcdd2\"\n")
		} else {
			sb.WriteString(prefix + r.IndentString + "fill: \"#ffebee\"\n")
		}
	case InternalBoundary:
		sb.WriteString(prefix + r.IndentString + "stroke: \"#2e7d32\"\n")
		sb.WriteString(prefix + r.IndentString + "fill: \"#e8f5e9\"\n")
	case BrowserBoundary:
		sb.WriteString(prefix + r.IndentString + "stroke: \"#1565c0\"\n")
		sb.WriteString(prefix + r.IndentString + "fill: \"#e3f2fd\"\n")
	case LocalhostBoundary:
		sb.WriteString(prefix + r.IndentString + "stroke: \"#7b1fa2\"\n")
		sb.WriteString(prefix + r.IndentString + "fill: \"#f3e5f5\"\n")
	case DMZBoundary:
		sb.WriteString(prefix + r.IndentString + "stroke: \"#f57c00\"\n")
		sb.WriteString(prefix + r.IndentString + "fill: \"#fff3e0\"\n")
	case WeakBoundary:
		sb.WriteString(prefix + r.IndentString + "stroke: \"#ff9800\"\n")
		sb.WriteString(prefix + r.IndentString + "stroke-dash: 8\n")
		sb.WriteString(prefix + r.IndentString + "fill: \"#fff8e1\"\n")
	default:
		sb.WriteString(prefix + r.IndentString + "stroke: \"#c62828\"\n")
		sb.WriteString(prefix + r.IndentString + "fill: transparent\n")
	}

	sb.WriteString(prefix + r.IndentString + "stroke-width: 2\n")
	sb.WriteString(prefix + r.IndentString + "border-radius: 10\n")
	sb.WriteString(prefix + "}\n\n")
}

func (r *Renderer) renderElement(sb *strings.Builder, e Element, indent int) {
	prefix := strings.Repeat(r.IndentString, indent)

	// Element declaration
	sb.WriteString(prefix + e.ID + ": " + e.Label + " {\n")

	// Shape
	shape := e.Type.D2Shape()
	sb.WriteString(prefix + r.IndentString + "shape: " + shape + "\n")

	// Style
	r.renderElementStyle(sb, e, indent+1)

	sb.WriteString(prefix + "}\n\n")
}

func (r *Renderer) renderElementStyle(sb *strings.Builder, e Element, indent int) {
	prefix := strings.Repeat(r.IndentString, indent)

	sb.WriteString(prefix + "style: {\n")

	// Type-specific colors
	switch e.Type {
	case Process:
		if e.Compromised {
			sb.WriteString(prefix + r.IndentString + "fill: \"#ffebee\"\n")
			sb.WriteString(prefix + r.IndentString + "stroke: \"#c62828\"\n")
			sb.WriteString(prefix + r.IndentString + "stroke-width: 3\n")
		} else {
			sb.WriteString(prefix + r.IndentString + "fill: \"#e3f2fd\"\n")
			sb.WriteString(prefix + r.IndentString + "stroke: \"#1976d2\"\n")
			sb.WriteString(prefix + r.IndentString + "stroke-width: 2\n")
		}
	case DataStore, Database:
		sb.WriteString(prefix + r.IndentString + "fill: \"#fff8e1\"\n")
		sb.WriteString(prefix + r.IndentString + "stroke: \"#ff8f00\"\n")
		sb.WriteString(prefix + r.IndentString + "stroke-width: 2\n")
	case ExternalEntity:
		if e.Compromised {
			sb.WriteString(prefix + r.IndentString + "fill: \"#ffcdd2\"\n")
			sb.WriteString(prefix + r.IndentString + "stroke: \"#b71c1c\"\n")
			sb.WriteString(prefix + r.IndentString + "stroke-width: 3\n")
		} else {
			sb.WriteString(prefix + r.IndentString + "fill: \"#fce4ec\"\n")
			sb.WriteString(prefix + r.IndentString + "stroke: \"#c2185b\"\n")
			sb.WriteString(prefix + r.IndentString + "stroke-width: 2\n")
		}
	case ExternalSystem:
		sb.WriteString(prefix + r.IndentString + "fill: \"#f3e5f5\"\n")
		sb.WriteString(prefix + r.IndentString + "stroke: \"#7b1fa2\"\n")
		sb.WriteString(prefix + r.IndentString + "stroke-width: 2\n")
	case Browser:
		sb.WriteString(prefix + r.IndentString + "fill: \"#e8f5e9\"\n")
		sb.WriteString(prefix + r.IndentString + "stroke: \"#388e3c\"\n")
		sb.WriteString(prefix + r.IndentString + "stroke-width: 2\n")
		sb.WriteString(prefix + r.IndentString + "border-radius: 8\n")
	case AIAgent:
		sb.WriteString(prefix + r.IndentString + "fill: \"#e8eaf6\"\n")
		sb.WriteString(prefix + r.IndentString + "stroke: \"#3f51b5\"\n")
		sb.WriteString(prefix + r.IndentString + "stroke-width: 2\n")
		sb.WriteString(prefix + r.IndentString + "border-radius: 8\n")
	case Gateway:
		sb.WriteString(prefix + r.IndentString + "fill: \"#e0f2f1\"\n")
		sb.WriteString(prefix + r.IndentString + "stroke: \"#00796b\"\n")
		sb.WriteString(prefix + r.IndentString + "stroke-width: 2\n")
	case ConfigStore:
		sb.WriteString(prefix + r.IndentString + "fill: \"#fce4ec\"\n")
		sb.WriteString(prefix + r.IndentString + "stroke: \"#c2185b\"\n")
		sb.WriteString(prefix + r.IndentString + "stroke-width: 2\n")
	default:
		sb.WriteString(prefix + r.IndentString + "fill: \"#f5f5f5\"\n")
		sb.WriteString(prefix + r.IndentString + "stroke: \"#9e9e9e\"\n")
		sb.WriteString(prefix + r.IndentString + "stroke-width: 2\n")
	}

	// Apply custom style overrides
	if e.Style != nil {
		if e.Style.Fill != "" {
			sb.WriteString(prefix + r.IndentString + "fill: \"" + e.Style.Fill + "\"\n")
		}
		if e.Style.Stroke != "" {
			sb.WriteString(prefix + r.IndentString + "stroke: \"" + e.Style.Stroke + "\"\n")
		}
		if e.Style.BorderRadius != 0 {
			fmt.Fprintf(sb, "%sborder-radius: %d\n", prefix+r.IndentString, e.Style.BorderRadius)
		}
	}

	sb.WriteString(prefix + "}\n")
}

func (r *Renderer) renderFlow(sb *strings.Builder, f Flow) {
	// Connection
	sb.WriteString(f.From + " -> " + f.To)

	// Label
	if f.Label != "" {
		sb.WriteString(": " + f.Label)
	}

	// Style
	sb.WriteString(" {\n")
	r.renderFlowStyle(sb, f)
	sb.WriteString("}\n\n")
}

func (r *Renderer) renderFlowStyle(sb *strings.Builder, f Flow) {
	prefix := r.IndentString

	switch f.Type {
	case AttackFlow:
		sb.WriteString(prefix + "style.stroke: \"#c62828\"\n")
		sb.WriteString(prefix + "style.stroke-width: 2\n")
		sb.WriteString(prefix + "style.stroke-dash: 3\n")
	case ExfilFlow:
		sb.WriteString(prefix + "style.stroke: \"#b71c1c\"\n")
		sb.WriteString(prefix + "style.stroke-width: 3\n")
		sb.WriteString(prefix + "style.stroke-dash: 5\n")
	case LateralFlow:
		sb.WriteString(prefix + "style.stroke: \"#e65100\"\n")
		sb.WriteString(prefix + "style.stroke-width: 2\n")
		sb.WriteString(prefix + "style.stroke-dash: 4\n")
	case C2Flow:
		sb.WriteString(prefix + "style.stroke: \"#4a148c\"\n")
		sb.WriteString(prefix + "style.stroke-width: 2\n")
		sb.WriteString(prefix + "style.stroke-dash: 3\n")
	default:
		sb.WriteString(prefix + "style.stroke: \"#424242\"\n")
	}

	// Apply custom style overrides
	if f.Style != nil {
		if f.Style.Stroke != "" {
			sb.WriteString(prefix + "style.stroke: \"" + f.Style.Stroke + "\"\n")
		}
		if f.Style.StrokeWidth != 0 {
			fmt.Fprintf(sb, "%sstyle.stroke-width: %d\n", prefix, f.Style.StrokeWidth)
		}
		if f.Style.StrokeDash != 0 {
			fmt.Fprintf(sb, "%sstyle.stroke-dash: %d\n", prefix, f.Style.StrokeDash)
		}
	}
}

func (r *Renderer) renderThreat(sb *strings.Builder, t stride.Threat) {
	sb.WriteString(t.D2ID() + ": " + t.Label() + " {\n")
	prefix := r.IndentString

	sb.WriteString(prefix + "style: {\n")

	// Use STRIDE colors
	color := t.Type.Color()
	sb.WriteString(prefix + prefix + "stroke: \"" + color + "\"\n")
	sb.WriteString(prefix + prefix + "stroke-width: 2\n")
	sb.WriteString(prefix + prefix + "border-radius: 8\n")
	sb.WriteString(prefix + prefix + "font-size: 12\n")

	sb.WriteString(prefix + "}\n")
	sb.WriteString("}\n\n")
}

// RenderToString is a convenience function that creates a renderer and renders the diagram.
func RenderToString(d *Diagram) string {
	r := NewRenderer()
	return r.Render(d)
}
